--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/WolvesFortresss/HeatmapChunkLoader
projects:
  HeatmapChunkLoader:
    path: ""
    libs:
      - src: CortexPE/Commando/Commando
        version: ^3.0.0
        branch: PM4
...
